ALTER TYPE "DisputeWorkflowStatus" ADD VALUE 'ATTESTATION_PENDING';
ALTER TYPE "DisputeWorkflowStatus" ADD VALUE 'ATTESTATION_READY';
ALTER TYPE "DisputeWorkflowStatus" ADD VALUE 'SETTLEMENT_PENDING';
ALTER TYPE "DisputeWorkflowStatus" ADD VALUE 'SETTLEMENT_SUBMITTED';
ALTER TYPE "DisputeWorkflowStatus" ADD VALUE 'SETTLED';
ALTER TYPE "DisputeWorkflowStatus" ADD VALUE 'REFUNDED';
ALTER TYPE "DisputeWorkflowStatus" ADD VALUE 'SETTLEMENT_UNKNOWN';
