ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'UPLOADED';
ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'READY_FOR_EXTRACTION';
ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'EXTRACTING';
ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'EXTRACTED';
ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'FAILED';
ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'OCR_REQUIRED';
ALTER TABLE "Document" ADD COLUMN "extractorVersion" TEXT, ADD COLUMN "processingError" TEXT, ADD COLUMN "extractionStartedAt" TIMESTAMP(3), ADD COLUMN "extractionCompletedAt" TIMESTAMP(3);
CREATE TABLE "RequirementSourceBlock" ("requirementId" TEXT NOT NULL, "sourceBlockId" TEXT NOT NULL, "precedence" INTEGER NOT NULL DEFAULT 0, CONSTRAINT "RequirementSourceBlock_pkey" PRIMARY KEY ("requirementId", "sourceBlockId"));
ALTER TABLE "RequirementSourceBlock" ADD CONSTRAINT "RequirementSourceBlock_requirementId_fkey" FOREIGN KEY ("requirementId") REFERENCES "Requirement"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RequirementSourceBlock" ADD CONSTRAINT "RequirementSourceBlock_sourceBlockId_fkey" FOREIGN KEY ("sourceBlockId") REFERENCES "SourceBlock"("id") ON DELETE CASCADE ON UPDATE CASCADE;
